pytorch基本数据抽象为张量，可以这样创建

In [12]:
import torch

uninitialized = torch.Tensor(3,2)
rand_initialized = torch.rand(3,2)
matrix_ones = torch.ones(3,2)
matrix_zeros = torch.zeros(3,2)

uninitialized, rand_initialized, matrix_ones, matrix_zeros

(tensor([[1.4411e+12, 3.0669e-41],
         [1.3756e+12, 3.0669e-41],
         [8.9683e-44, 0.0000e+00]]),
 tensor([[0.5275, 0.9302],
         [0.6251, 0.0768],
         [0.8794, 0.5663]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]))

调用shape属性，或通过size可以获取张量的形状

张量也可进行切片操作。

In [8]:
size = rand_initialized.size()
shape = rand_initialized.shape
print(size == shape)

True


shape对象继承自元组，不可变

In [10]:
print(shape[0])

3


张量对象满足python数值运算，运算符与普通运算符一样

In [15]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
y = torch.ones(3,2) + 2
y

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [16]:
z = torch.ones(2,1)
z

tensor([[1.],
        [1.]])

In [17]:
x * y @ z

tensor([[6.],
        [6.],
        [6.]])

乘法运算符执行元素乘法，@运算符为矩阵乘法，也可用函数mm或matmul完成。
存在多种用于张量操作的选项，python运算符，in-place的pytorch函数与out-place的pytorch函数。
add不改变被加数，add_会改变（即in-place）。
具有in-place特性的操作会在最后加一个下划线。

In [18]:
x = x.add(y)
x

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

In [19]:
z = x.add_(y)
z

tensor([[7., 7.],
        [7., 7.],
        [7., 7.]])

In [20]:
x = torch.rand(2,3)
y = torch.rand(3,4)
x.matmul(y)

tensor([[1.3371, 0.9340, 1.1710, 0.3482],
        [2.1146, 1.3626, 1.8980, 0.5046]])

index类似于标准的python列表，可以使用index_select()进行索引

In [21]:
# 创建1D张量
a = torch.arange(0, 9)
print(a)
# 获取1D张量的第1个维度且索引号为2和3的张量子集
print(torch.index_select(a, dim = 0, index = torch.tensor([2, 3])))

# 创建2D张量
b = torch.arange(0, 9).view([3, 3])
print(b)
# 获取2D张量的第2个维度且索引号为0和1的张量子集(第一列和第二列)
print(torch.index_select(b, dim = 1, index = torch.tensor([0, 1])))

# 创建3D张量
c = torch.arange(0, 9).view([1, 3, 3])
print(c)
# 获取3D张量的第1个维度且索引号为0的张量子集
print(torch.index_select(c, dim = 0, index = torch.tensor([0])))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [3, 4],
        [6, 7]])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


连接是另一个重要操作，cat可以对只有一个维度大小不同的两个张量进行连接。

In [22]:
a = torch.rand(3,2,4)
b = torch.rand(3,5,4)
#将a与b在第一个维度上拼接
c = torch.cat((a,b), 1)
c

tensor([[[0.4752, 0.1972, 0.6006, 0.7660],
         [0.2700, 0.5702, 0.9233, 0.2681],
         [0.9825, 0.6635, 0.2156, 0.8382],
         [0.1175, 0.3444, 0.6000, 0.6853],
         [0.8817, 0.1497, 0.2189, 0.3294],
         [0.6550, 0.9965, 0.6749, 0.5816],
         [0.4026, 0.9828, 0.5191, 0.8205]],

        [[0.3660, 0.1144, 0.9643, 0.7446],
         [0.0202, 0.1803, 0.6829, 0.7139],
         [0.7678, 0.4584, 0.5009, 0.3447],
         [0.2344, 0.8605, 0.4351, 0.6416],
         [0.8061, 0.5186, 0.2129, 0.7069],
         [0.9755, 0.4493, 0.8917, 0.4941],
         [0.9799, 0.5296, 0.8898, 0.1977]],

        [[0.2407, 0.9414, 0.5146, 0.3085],
         [0.6784, 0.4069, 0.8438, 0.4519],
         [0.6926, 0.8479, 0.9288, 0.3499],
         [0.1628, 0.4967, 0.1928, 0.0581],
         [0.2368, 0.2999, 0.4323, 0.8609],
         [0.9316, 0.6592, 0.9398, 0.5932],
         [0.3054, 0.6573, 0.4194, 0.1188]]])

如果要向张量中添加新维度，使用stack。
对于torch.stack来说，会先将原始数据维度扩展一维，
然后再按照维度进行拼接，具体拼接操作同torch.cat类似。

In [23]:
a0=torch.Tensor([[[[1,1,1,1],[2,2,2,2]]]])
a1=torch.Tensor([[[[3,3,3,3],[4,4,4,4]]]])
torch.stack((a0,a1),dim=0).type(torch.FloatTensor)

tensor([[[[[1., 1., 1., 1.],
           [2., 2., 2., 2.]]]],



        [[[[3., 3., 3., 3.],
           [4., 4., 4., 4.]]]]])

split与chunk用于拆分张量，split接受每个输出张量的期望大小。
对tensor在某一dim维度下，根据指定的大小split_size=int，或者list(int)来分割数据，返回张量列表。

注意两个细节：1、当split_size为一个int数时，若不能整除int，剩余的数据直接作为一块。
2、当split_size为一个列表时，所有数字的和等于要分割的维度大小。

In [26]:
#细节1
input1 = torch.randn(4,10,8)
output1 = torch.split(input1, 3, dim=1) #3+3+3+1=10,不够的单独作为一块
print(type(output1))
for chunk in output1:
    print(chunk.size())

#细节2
input2 = torch.randn(4,10,8)
split_list = [3, 3, 3, 1]
output2 = torch.split(input2, split_list, dim=1) #3+3+3+1=10
print(type(output2))
for chunk in output2:
    print(chunk.size())

<class 'tuple'>
torch.Size([4, 3, 8])
torch.Size([4, 3, 8])
torch.Size([4, 3, 8])
torch.Size([4, 1, 8])
<class 'tuple'>
torch.Size([4, 3, 8])
torch.Size([4, 3, 8])
torch.Size([4, 3, 8])
torch.Size([4, 1, 8])


chunk方法可以对张量分块，返回一个张量列表。
同上，若不能整除int，剩余的数据直接作为一块。

区别：
（1）chunks只能是int型，而split_size_or_section可以是list。

（2）chunks在时，不满足该维度下的整除关系，会将块按照维度切分成1的结构。

In [34]:
input1 = torch.randn(4,10,8)
output1 = torch.chunk(input1, 11, dim=1)
print(type(output1))
for chunk in output1:
    print(chunk.size())

output2 = torch.split(input1, 11, dim=1)
for chunk in output2:
    print(chunk.size())

<class 'tuple'>
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
torch.Size([4, 1, 8])
tensor([[[-8.7442e-01,  5.5963e-03, -1.5089e+00,  1.8815e-01, -1.0905e+00,
          -8.7135e-01, -7.3811e-04, -7.0268e-01],
         [-6.0521e-01,  2.6147e-01,  4.1766e-01, -3.5814e-01,  3.4403e-01,
          -2.9477e-01, -7.8140e-01,  1.0379e+00],
         [-4.3601e-01,  8.8101e-01, -5.2223e-01,  7.6835e-01,  7.5641e-01,
          -7.0552e-02, -9.1096e-01, -1.7755e+00],
         [-2.1190e-01,  6.7628e-01, -9.9943e-01, -1.9734e-01,  1.9756e+00,
           1.3190e+00, -4.8041e-02,  6.7685e-01],
         [ 3.4251e-01, -1.4634e+00,  8.4958e-01,  8.8005e-01,  4.8116e-01,
          -7.5287e-01, -2.2062e-01, -1.4990e-01],
         [-2.3055e-01, -2.1300e+00, -5.1149e-01,  5.2352e-02,  1.1980e-01,
          -8.4235e-02, -1.1027e+00, -1.0226e+00],
         [-7.6

squeeze可以删除尺寸为1的维度。
unsqueeze就是增加一维。

In [40]:
a = torch.rand(1,2,3)
a.squeeze(0)

tensor([[0.9699, 0.3483, 0.6220],
        [0.4750, 0.3475, 0.8540]])

In [39]:
a = torch.rand(1,2,3)
a.unsqueeze(0)

tensor([[[[0.4190, 0.6260, 0.0429],
          [0.0024, 0.0396, 0.0181]]]])

对张量使用cuda方法可以将张量从cpu搬到gpu。
再次调用cpu可以搬回来。

在那以前先确认是否可以使用gpu。

In [41]:
torch.cuda.is_available()

True

In [42]:
a.cuda()

tensor([[[0.9699, 0.3483, 0.6220],
         [0.4750, 0.3475, 0.8540]]], device='cuda:0')

In [43]:
a.cpu()

tensor([[[0.9699, 0.3483, 0.6220],
         [0.4750, 0.3475, 0.8540]]])

In [45]:
torch.cuda.device_count() #返回gpu数量。

1

In [46]:
torch.cuda.get_device_name(0) #返回gpu名字,设备索引默认从0开始。

'GeForce GTX 1660 Ti'

运算速度对比：

In [47]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

a.matmul(b)

tensor([[2502.1125, 2492.1038, 2504.5610,  ..., 2474.5330, 2500.9622,
         2491.8679],
        [2505.2708, 2517.1235, 2485.7771,  ..., 2480.0925, 2502.1731,
         2503.4441],
        [2496.4150, 2527.9297, 2504.4768,  ..., 2503.2703, 2515.6689,
         2505.7969],
        ...,
        [2530.3528, 2528.3135, 2516.9395,  ..., 2486.0198, 2502.7905,
         2520.9678],
        [2512.1865, 2517.8069, 2491.5547,  ..., 2494.9976, 2506.6116,
         2518.1348],
        [2502.6599, 2507.1782, 2494.0054,  ..., 2474.8340, 2505.6025,
         2505.6494]])

In [49]:
a = a.cuda()
b = b.cuda()

a.matmul(b)


tensor([[2502.1055, 2492.1025, 2504.5554,  ..., 2474.5310, 2500.9602,
         2491.8738],
        [2505.2664, 2517.1260, 2485.7825,  ..., 2480.0928, 2502.1724,
         2503.4448],
        [2496.4104, 2527.9282, 2504.4783,  ..., 2503.2683, 2515.6721,
         2505.7969],
        ...,
        [2530.3596, 2528.3137, 2516.9390,  ..., 2486.0212, 2502.7959,
         2520.9714],
        [2512.1887, 2517.7974, 2491.5576,  ..., 2494.9917, 2506.6116,
         2518.1335],
        [2502.6621, 2507.1868, 2494.0100,  ..., 2474.8340, 2505.6055,
         2505.6458]], device='cuda:0')