标准的Python数据结构是一个单层内存对象。但Pytorch的数据结构是分层设计的，内存效率高。
为了加速，内核的计算密集部分已迁移到C/C++后端。Pytorch面向对象的数据结构是一个THTensor对象，保存
有关维度，偏移，步长等信息。THTensor存储的另一个主要信息是指向THStorage的指针，它是为存储而保留的
张量对象的内部层。THStorage负责保持指针指向原始数据和分配器。下面是一些实例：

创建2*2的x张量。然后创建它的另一个视图xv。最后调用numpy创建Numpy数组。


In [1]:
import torch
import numpy as np

x = torch.ones(2,2)
xv = x.view(-1)
xn = x.numpy()
print(x)
print(xv)
print(xn)

tensor([[1., 1.],
        [1., 1.]])
tensor([1., 1., 1., 1.])
[[1. 1.]
 [1. 1.]]


storage方法返回THStorage对象，它的data_ptr指向原始数据对象。
可以看到x与xv是相同的。


In [2]:
x.storage()

 1.0
 1.0
 1.0
 1.0
[torch.FloatStorage of size 4]

In [3]:
xv.storage()

 1.0
 1.0
 1.0
 1.0
[torch.FloatStorage of size 4]

In [4]:
x.storage().data_ptr() == xv.storage().data_ptr()

True