1.层--神经网络的基本组成

最重要的一种是线性层，如：

In [6]:
from torch.nn import Linear
from torch.autograd import Variable
import torch
import torch.nn as nn

myLayer = Linear(in_features=10, out_features=5, bias=True)
inp = Variable(torch.randn(1,10))
myLayer(inp)

tensor([[ 0.8152, -0.7249,  1.0178, -0.9301, -0.1114]],
       grad_fn=<AddmmBackward>)

可以使用属性weights和bias访问层的可训练参数。

In [2]:
myLayer.weight

Parameter containing:
tensor([[-0.0588, -0.1034,  0.1875,  0.0318, -0.3108, -0.2996, -0.2199,  0.0197,
         -0.1492, -0.0215],
        [-0.0878, -0.2875,  0.1953, -0.2660,  0.2925, -0.1067, -0.2141, -0.2479,
          0.2666,  0.0757],
        [-0.1316, -0.1513,  0.1597, -0.2969, -0.1682,  0.0738, -0.2633, -0.0691,
          0.2258, -0.2845],
        [ 0.1739, -0.0897,  0.0947,  0.2147,  0.0351, -0.2237,  0.0652,  0.0528,
         -0.0804, -0.1180],
        [ 0.1792, -0.0443, -0.1721, -0.1628, -0.2420,  0.2688,  0.1696, -0.0314,
          0.1419,  0.2344]], requires_grad=True)

In [3]:
myLayer.bias

Parameter containing:
tensor([-0.0976,  0.2117,  0.1996, -0.0337,  0.1045], requires_grad=True)

但一般不止一个层。
可以通过把一层的输出传给另一层实现。

In [4]:
myLayerx = Linear(5,2)
myLayerx(myLayer(inp))

tensor([[-0.5846,  0.4345]], grad_fn=<AddmmBackward>)

只堆叠多个线性层没有任何意义。
可以使用不同的非线性函数。

2.非线性激活函数

（1）sigmoid
（2）tanh
（3）ReLU
（4）Leaky ReLU

In [7]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
myrelu = nn.ReLU()
myrelu(sample_data)

tensor([[1., 2., 0., 0.]])

3.损失函数

优化器通常接受标量。因而loss函数应该生成一个标量值，并使其在训练期间最小化。
以MSE均方误差为例。

In [8]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5), requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input, target)
output.backward()

4.优化器

以SGD为例

In [ ]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)